dofile('test-resources/native-cargo/state.lua')
local count, nativeAssert = 0, assert
local function assert(...) count = count + 1; return nativeAssert(...) end
local row = CargoState.new()
assert(not CargoState.reserve(row, 'ped', 'alice', 0, false), 'distance/phase precondition required')
assert(CargoState.reserve(row, 'ped', 'alice', 0, true))
local token = row.revision
assert(not CargoState.reserve(row, 'ped2', 'bob', 1, true), 'one executor per object')
assert(not CargoState.report(row, 'bob', token, 'holding', 1), 'reject observer reports')
assert(not CargoState.report(row, 'alice', token - 1, 'holding', 1), 'reject stale reports')
assert(not CargoState.report(row, 'alice', token, 'delivered', 1), 'no client delivery authority')
assert(not CargoState.report(row, 'alice', token, 'putting_down', 1), 'cannot skip hold acknowledgement')
assert(not CargoState.report(row, 'alice', token, 'holding', 8000), 'expired acknowledgement cannot revive pending lease')
assert(CargoState.expired(row, 8000), 'failed construction recovers within deadline')
assert(CargoState.report(row, 'alice', token, 'holding', 10))
assert(not CargoState.expired(row, 100000), 'walking has no arbitrary time limit')
assert(not CargoState.report(row, 'alice', token, 'holding', 20), 'duplicate cannot extend a lease')
assert(CargoState.report(row, 'alice', token, 'putting_down', 30))
assert(CargoState.expired(row, 8030), 'putdown cannot wait forever')
assert(CargoState.report(row, 'alice', token, 'released', 40))
assert(row.phase == 'available' and row.ped == nil and row.executor == nil)
assert(not CargoState.report(row, 'alice', token, 'holding', 50), 'late reports cannot resurrect cargo')
assert(CargoState.reserve(row, 'ped2', 'bob', 60, true))
assert(not CargoState.report(row, 'alice', token, 'released', 70), 'previous owner cannot cancel new owner')
assert(CargoState.release(row), 'death/disconnect/streaming/ownership loss use same invalidation')
assert(not CargoState.release(row), 'release is idempotent')
print('native-cargo state: ' .. count .. ' assertions passed')
