#!/usr/bin/env python3
"""Generate the checked-in vanilla ambient-ped catalog used by the test runtime."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


ZONE_PATTERN = re.compile(
    r'^\s*\{"([A-Z0-9]+)",\s*(\d+),\s*(\d+),\s*(\d+),\s*(true|false),\s*\{([^}]*)\}\},\s*$'
)
COP_MODELS_BY_LEVEL = [283, 280, 281, 282]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_peds(path: Path) -> dict[str, dict[str, object]]:
    models: dict[str, dict[str, object]] = {}
    for raw_line in path.read_text(encoding="latin-1").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line in {"peds", "end"}:
            continue
        fields = [field.strip() for field in line.split(",")]
        if len(fields) < 6 or not fields[0].isdigit():
            continue
        model_id = int(fields[0])
        if not 0 <= model_id <= 288:
            continue
        name = fields[1].upper()
        models[name] = {
            "id": model_id,
            "name": name,
            "nativePedType": fields[3].upper(),
            "pedStats": fields[4].upper(),
            "animGroup": fields[5].lower(),
        }
    return models


def parse_ped_groups(path: Path, models: dict[str, dict[str, object]]) -> tuple[dict[int, int], list[int], dict[int, int]]:
    gang_by_model: dict[int, int] = {}
    dealer_models: list[int] = []
    civilian_types: dict[int, int] = {}
    reached_gangs = False

    for raw_line in path.read_text(encoding="latin-1").splitlines():
        values_text, _, comment = raw_line.partition("#")
        names = [value.strip().upper() for value in values_text.split(",") if value.strip()]
        if not names:
            continue

        gang_match = re.search(r"\bGang\s+(\d+)\b", comment, re.IGNORECASE)
        if gang_match:
            reached_gangs = True
            gang_id = int(gang_match.group(1)) - 1
            for name in names:
                model = models.get(name)
                if model:
                    # Retail gang slots 8/9 reuse the VLA models from gang 7.
                    # Preserve the first identity so the catalog never makes
                    # those shared models authenticate as the unused slots.
                    gang_by_model.setdefault(int(model["id"]), gang_id)
            continue

        if comment.strip().lower().startswith("dealers"):
            reached_gangs = True
            dealer_models = [int(models[name]["id"]) for name in names if name in models]
            continue

        if reached_gangs:
            continue
        for name in names:
            model = models.get(name)
            if not model:
                continue
            native_type = model["nativePedType"]
            if native_type == "CIVMALE":
                civilian_types[int(model["id"])] = 4
            elif native_type == "CIVFEMALE":
                civilian_types[int(model["id"])] = 5

    return gang_by_model, dealer_models, civilian_types


def parse_zones(path: Path) -> dict[str, dict[str, object]]:
    zones: dict[str, dict[str, object]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ZONE_PATTERN.match(line)
        if not match:
            continue
        label, population_type, races, dealer_strength, no_cops, gang_values = match.groups()
        gangs = [int(value.strip()) for value in gang_values.split(",")]
        if len(gangs) != 10:
            raise ValueError(f"zone {label} has {len(gangs)} gang strengths")
        zones[label] = {
            "populationType": int(population_type),
            "races": int(races),
            "dealerStrength": int(dealer_strength),
            "noCops": no_cops == "true",
            "gangStrengths": gangs,
        }
    return zones


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_catalog(
    models: dict[str, dict[str, object]],
    gang_by_model: dict[int, int],
    dealer_models: list[int],
    civilian_types: dict[int, int],
    zones: dict[str, dict[str, object]],
    source_hashes: dict[str, str],
) -> str:
    model_rows = sorted(models.values(), key=lambda model: int(model["id"]))
    revision_payload = {
        "models": model_rows,
        "gangByModel": gang_by_model,
        "dealerModels": dealer_models,
        "copModelsByLevel": COP_MODELS_BY_LEVEL,
        "civilianPedTypeByModel": civilian_types,
        "zones": zones,
        "sources": source_hashes,
    }
    revision = hashlib.sha256(json.dumps(revision_payload, sort_keys=True, separators=(",", ":")).encode()).hexdigest()

    lines = [
        "-- Generated by utils/generate-ambient-ped-catalog.py; do not edit by hand.",
        "-- Inputs are the retail GTA SA 1.0 US data files and Neon's audited main.scm zone bootstrap.",
        "PedTrafficPopulationCatalog = {",
        "    schema = 1,",
        f"    revision = {lua_string(revision)},",
        "    sources = {",
    ]
    for name, digest in sorted(source_hashes.items()):
        lines.append(f"        [{lua_string(name)}] = {lua_string(digest)},")
    lines.extend(["    },", "    models = {"])
    for model in model_rows:
        model_id = int(model["id"])
        lines.append(
            f"        [{model_id}] = {{name = {lua_string(str(model['name']))}, nativePedType = {lua_string(str(model['nativePedType']))}, "
            f"pedStats = {lua_string(str(model['pedStats']))}, animGroup = {lua_string(str(model['animGroup']))}}},"
        )
    lines.extend(["    },", "    civilianPedTypeByModel = {"])
    for model_id, ped_type in sorted(civilian_types.items()):
        lines.append(f"        [{model_id}] = {ped_type},")
    lines.extend(["    },", "    gangByModel = {"])
    for model_id, gang_id in sorted(gang_by_model.items()):
        lines.append(f"        [{model_id}] = {gang_id},")
    lines.extend(["    },", "    dealerModels = {"])
    for index, model_id in enumerate(dealer_models, 1):
        lines.append(f"        [{index}] = {model_id},")
    lines.extend(["    },", "    copModelsByLevel = {"])
    for level, model_id in enumerate(COP_MODELS_BY_LEVEL):
        lines.append(f"        [{level}] = {model_id},")
    lines.extend(["    },", "    zones = {"])
    for label, zone in sorted(zones.items()):
        gangs = ", ".join(str(value) for value in zone["gangStrengths"])
        lines.append(
            f"        [{lua_string(label)}] = {{populationType = {zone['populationType']}, races = {zone['races']}, "
            f"dealerStrength = {zone['dealerStrength']}, noCops = {str(zone['noCops']).lower()}, gangStrengths = {{{gangs}}}}},"
        )
    lines.extend(["    },", "}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gta-data", type=Path, required=True, help="Path to GTA San Andreas/data")
    parser.add_argument(
        "--zones",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "Client/game_sa/AmbientPedPopulationZonesSA.inc",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "official-resources/native-ped-traffic/population_catalog.lua",
    )
    args = parser.parse_args()

    paths = {
        "pedgrp.dat": args.gta_data / "pedgrp.dat",
        "peds.ide": args.gta_data / "peds.ide",
        "pedstats.dat": args.gta_data / "pedstats.dat",
        "ped.dat": args.gta_data / "ped.dat",
        "AmbientPedPopulationZonesSA.inc": args.zones,
    }
    for path in paths.values():
        if not path.is_file():
            raise FileNotFoundError(path)

    models = parse_peds(paths["peds.ide"])
    gang_by_model, dealer_models, civilian_types = parse_ped_groups(paths["pedgrp.dat"], models)
    zones = parse_zones(args.zones)
    if dealer_models != [28, 29, 30, 254]:
        raise ValueError(f"unexpected DEALERS group: {dealer_models}")
    for model_id in COP_MODELS_BY_LEVEL:
        model = next((entry for entry in models.values() if entry["id"] == model_id), None)
        if not model or model["nativePedType"] != "COP":
            raise ValueError(f"unexpected city-cop model {model_id}: {model}")
    if len(zones) != 336:
        raise ValueError(f"unexpected zone count: {len(zones)}")

    args.output.write_text(
        render_catalog(models, gang_by_model, dealer_models, civilian_types, zones, {name: sha256(path) for name, path in paths.items()}),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
